### **PyTorch NN Module**

In [92]:
import numpy as np
import pandas as pd
import torch

# Data Preprocessing Libraries
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [93]:
# Using Breast Cancer Detection Dataset

df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [94]:
df.shape

(569, 33)

In [95]:
df.drop(['id', 'Unnamed: 32'], axis=1, inplace=True)

In [96]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [97]:
# Splitting the dataset into features and target variable
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [98]:
# scalar object
scaler = StandardScaler()

# 
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [99]:
X_train

array([[ 0.62933084,  0.30423636,  0.63243437, ...,  0.64608091,
         0.29528265, -0.123416  ],
       [-0.18526778, -1.55719333, -0.27062689, ..., -1.45702718,
        -1.01094165, -1.22054853],
       [-0.54698486, -0.34493724, -0.58058851, ..., -0.32641357,
         0.84527183, -0.83589649],
       ...,
       [-0.12351121,  0.33215781, -0.07860396, ...,  0.60438934,
         0.44059229,  1.68510425],
       [ 1.86740312,  0.4787454 ,  1.7224093 , ...,  0.43299066,
        -1.05625326, -0.70968254],
       [-1.07338614,  0.10645946, -1.07831534, ..., -0.75815294,
        -0.04846059, -0.3703801 ]], shape=(455, 30))

In [100]:
y_train

328    M
308    B
409    B
73     M
20     B
      ..
490    B
314    B
7      M
237    M
245    B
Name: diagnosis, Length: 455, dtype: object

In [101]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)


In [102]:
y_train

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,

In [103]:
# Converting numpy arrays to torch tensors

X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()

y_train_tensor = torch.from_numpy(y_train).float().unsqueeze(1)
y_test_tensor = torch.from_numpy(y_test).float().unsqueeze(1)

In [104]:
X_train_tensor.shape
print(X_train_tensor)

tensor([[ 0.6293,  0.3042,  0.6324,  ...,  0.6461,  0.2953, -0.1234],
        [-0.1853, -1.5572, -0.2706,  ..., -1.4570, -1.0109, -1.2205],
        [-0.5470, -0.3449, -0.5806,  ..., -0.3264,  0.8453, -0.8359],
        ...,
        [-0.1235,  0.3322, -0.0786,  ...,  0.6044,  0.4406,  1.6851],
        [ 1.8674,  0.4787,  1.7224,  ...,  0.4330, -1.0563, -0.7097],
        [-1.0734,  0.1065, -1.0783,  ..., -0.7582, -0.0485, -0.3704]])


In [105]:
y_train_tensor.shape
print(f"Shapes verified: X={X_train_tensor.shape}, y={y_train_tensor.shape}")

Shapes verified: X=torch.Size([455, 30]), y=torch.Size([455, 1])


In [106]:
# Create Model Class
import torch.nn as nn

# nn.Module as a blueprint provided by PyTorch. 
# By saying class NeuralNet(nn.Module), we are telling python to use all the super powers of PyTorch's nn.Module class.
class NeuralNet(nn.Module):
    
    def __init__(self, num_features):
        super().__init__() # <--- The "Boilerpalte" line.

        # This is the "Stack of Layers" that we will use in our Neural Network.
        # (Pipe)Sequential is a container that allows us to stack layers together.
        self.network = nn.Sequential(

            # Layer 1 : The input layer -> hidden layer
            nn.Linear(num_features, 16),

            # Layer 1 : The "Spark" : The activation function introduces non-linearity to the model.
            nn.ReLU(),

            # Layer 2 : The hidden layer -> output layer
            nn.Linear(16, 8),
            nn.ReLU(),

            # Layer 3 : The output layer
            nn.Linear(8, 1),
            # The "Squish" : The activation function for output layer to convert it to probability.
            nn.Sigmoid()
        )

    # 
    def forward(self, features):
        out = self.network(features) # <--- Pass data through the pipe we made above
        return out

In [107]:
# create dataset
features = X_train_tensor

# Create model
model = NeuralNet(features.shape[1])

## call the model for forward pass
# model.forward(features)
prediction = model(features)

In [108]:
# show model weights
model.network[0].weight

Parameter containing:
tensor([[-0.1251, -0.1067, -0.1271,  0.0826, -0.0015, -0.0500, -0.0135,  0.1069,
          0.1374,  0.0174,  0.1238, -0.1361,  0.0043,  0.0966,  0.0713, -0.1529,
          0.1424, -0.0549, -0.1339,  0.1207,  0.1212, -0.1241,  0.1741, -0.1248,
         -0.0656, -0.1685, -0.0507,  0.1139,  0.1690,  0.1797],
        [-0.0740, -0.1360, -0.0417, -0.1331,  0.0707,  0.1068, -0.1641,  0.1215,
          0.0537,  0.1350,  0.0682,  0.0453, -0.0336,  0.0304, -0.1020, -0.1433,
          0.0852,  0.1315,  0.1267,  0.1547,  0.0322, -0.1352,  0.0278,  0.1220,
         -0.0890,  0.0803,  0.0140, -0.1510, -0.0960,  0.1166],
        [-0.0424,  0.1087, -0.1617,  0.0011,  0.0236,  0.1445, -0.1203,  0.0576,
          0.1794, -0.0170, -0.0319,  0.0079, -0.0324, -0.1386, -0.0572, -0.0139,
          0.1437, -0.0835,  0.0149, -0.0333, -0.0907, -0.0032,  0.0283,  0.0576,
         -0.1246, -0.1319, -0.0400, -0.0179,  0.1559,  0.0040],
        [-0.0092, -0.0079,  0.1720, -0.1376,  0.0255, -0.

In [109]:
# Calculating loss (The scoreboard) 
# "BCELoss" stands for Binary Cross Entropy !
criterion = nn.BCELoss()

# this will update the weights of the model
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

# calcualte loss using the criterion
loss = criterion(prediction,  y_train_tensor)

# backpropagation
loss.backward()
optimizer.step()

The Trainigng Loop (The learning Phase)

In [110]:
num_epochs = 100
for epoch in range(num_epochs):
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(features)

    # Calculate Loss
    loss = criterion(y_pred, y_train_tensor)
    
    # Back propagation
    optimizer.zero_grad() # clear previous gradients (Crucial step)
    loss.backward()
    optimizer.step()    # update weights

    # Print loss every 10 epochs
    if (epoch+1) % 10 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

Epoch [10/100], Loss: 0.2510
Epoch [20/100], Loss: 0.0913
Epoch [30/100], Loss: 0.0598
Epoch [40/100], Loss: 0.0472
Epoch [50/100], Loss: 0.0381
Epoch [60/100], Loss: 0.0319
Epoch [70/100], Loss: 0.0260
Epoch [80/100], Loss: 0.0208
Epoch [90/100], Loss: 0.0160
Epoch [100/100], Loss: 0.0121
Epoch [70/100], Loss: 0.0260
Epoch [80/100], Loss: 0.0208
Epoch [90/100], Loss: 0.0160
Epoch [100/100], Loss: 0.0121


In [111]:
model.eval()  # set the model to evaluation mode

with torch.no_grad():
    y_test_pred = model(X_test_tensor)
    y_test_pred_cls = y_test_pred.round()  # Convert probabilities to 0 or 1
    accuracy = (y_test_pred_cls.eq(y_test_tensor).sum().item()) / y_test_tensor.shape[0]
    print(f'Accuracy: {accuracy * 100:.2f}%')

Accuracy: 99.12%


In [112]:
%pip install torchinfo

Note: you may need to restart the kernel to use updated packages.


In [113]:
from torchinfo import summary

# input_size format: (batch_size, num_features)
# Your dataset has 30 features, so use (1, 30) for a single sample
summary(model, input_size=(1, 30))

Layer (type:depth-idx)                   Output Shape              Param #
NeuralNet                                [1, 1]                    --
├─Sequential: 1-1                        [1, 1]                    --
│    └─Linear: 2-1                       [1, 16]                   496
│    └─ReLU: 2-2                         [1, 16]                   --
│    └─Linear: 2-3                       [1, 8]                    136
│    └─ReLU: 2-4                         [1, 8]                    --
│    └─Linear: 2-5                       [1, 1]                    9
│    └─Sigmoid: 2-6                      [1, 1]                    --
Total params: 641
Trainable params: 641
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00