# PyTorch For Deep Learning

In [ ]:
# import torch 
import torch  # type: ignore
print(torch.__version__)

2.9.0+cu126


In [ ]:
# Check for GPU availability

if torch.cuda.is_available():
    print("CUDA is available. GPU will be used for computations.")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("CUDA is not available. Using CPU for computations.")


CUDA is available. GPU will be used for computations.
Using GPU: Tesla T4


### Creating a Tensor

In [ ]:
 # using empty 
# .empty => create a empty memory tensor
x = torch.empty(2,3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 1.1351e-43],
        [0.0000e+00, 7.8805e-19, 0.0000e+00]])


In [12]:
 # check type
print(type(x))

<class 'torch.Tensor'>


In [14]:
 # using zeros
y = torch.zeros(2,3)
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [15]:
 # using ones
z = torch.ones(2,3)
print(z)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [17]:
# using rand
# creates tensor with random values between 0 and 1
a = torch.rand(2,3)
print(a)

tensor([[0.8979, 0.7703, 0.3350],
        [0.2598, 0.6175, 0.9625]])


In [ ]:
 # use of seed
a = torch.rand(2,3)  # generates different random numbers each time
torch.manual_seed(42)  # sets the seed for generating random numbers
print(torch.rand(2,3)) 

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [19]:
 # manual seed
torch.manual_seed(30)
print(torch.rand(2,3))


tensor([[0.9007, 0.7464, 0.4716],
        [0.8738, 0.7403, 0.7840]])


In [ ]:
# using tensors

# create a tensor from a list
t1 = torch.tensor([[1,2,3],[4,5,6]])
print(t1)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [22]:
# other ways

# arange 
print("Using  arange : ",torch.arange(0,10,3))  


Using  arange :  tensor([0, 3, 6, 9])
