# PyTorch For Deep Learning

In [23]:
# import torch 
import torch 
print(torch.__version__)

2.9.0+cu126


In [24]:
# Check for GPU availability

if torch.cuda.is_available():
    print("CUDA is available. GPU will be used for computations.")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("CUDA is not available. Using CPU for computations.")


CUDA is available. GPU will be used for computations.
Using GPU: Tesla T4


### Creating a Tensor

In [25]:
 # using empty 
# .empty => create a empty memory tensor
x = torch.empty(2,3)
print(x)

tensor([[1.3586e-21, 4.5720e-41, 1.5419e-03],
        [0.0000e+00, 2.5205e-09, 2.6252e-06]])


In [26]:
 # check type
print(type(x))

<class 'torch.Tensor'>


In [27]:
 # using zeros
y = torch.zeros(2,3)
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [28]:
 # using ones
z = torch.ones(2,3)
print(z)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [29]:
# using rand
# creates tensor with random values between 0 and 1
a = torch.rand(2,3)
print(a)

tensor([[0.8946, 0.6238, 0.4276],
        [0.8421, 0.7454, 0.6181]])


In [30]:
 # use of seed
a = torch.rand(2,3)  # generates different random numbers each time
torch.manual_seed(42)  # sets the seed for generating random numbers
print(torch.rand(2,3)) 

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [31]:
 # manual seed
torch.manual_seed(30)
print(torch.rand(2,3))


tensor([[0.9007, 0.7464, 0.4716],
        [0.8738, 0.7403, 0.7840]])


In [32]:
# using tensors

# create a tensor from a list
t1 = torch.tensor([[1,2,3],[4,5,6]])
print(t1)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [33]:
# other ways

# arange 
print("Using  arange : ",torch.arange(0,10,3))  

# linspace
print("Using linspace : ",torch.linspace(0,10,5))

# using eye
# creates identity matrix
print("Using eye : ",torch.eye(3,4))  

# using full
# creates tensor filled with specified value
print("Using full : ",torch.full((2,3),7))

Using  arange :  tensor([0, 3, 6, 9])
Using linspace :  tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
Using eye :  tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])
Using full :  tensor([[7, 7, 7],
        [7, 7, 7]])


### Tensor Shapes

In [34]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [35]:
# shape of tensor
x.shape

torch.Size([2, 3])

In [36]:
torch.empty_like(x)

tensor([[140132381183376,       985193008,       986309792],
        [      906342864,               0,       986478208]])

In [37]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [40]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

### Tensor Data Types

In [42]:
# find data type
x.dtype

torch.int64

In [43]:
# assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [45]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float32)

tensor([1., 2., 3.])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical 
operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical Operations

### 1. Scalar Operations

In [57]:
x = torch.rand(2,2)
x

tensor([[0.1748, 0.3426],
        [0.9377, 0.0413]])

In [60]:
# addition => add 2 to each element
x + 2

print(x)
# subtraction => subtract 2 from each element
x - 2
print(x)

# multiplication => multiply each element by 2
x * 2
print(x)

# division => divide each element by 2
x / 2
print(x)

# int division => floor division of each element by 2
x // 2
print(x)

# modulus => remainder of each element divided by 2
x % 2
print(x)

# power => each element raised to the power of 2
x ** 2
print(x)

tensor([[0.1748, 0.3426],
        [0.9377, 0.0413]])
tensor([[0.1748, 0.3426],
        [0.9377, 0.0413]])
tensor([[0.1748, 0.3426],
        [0.9377, 0.0413]])
tensor([[0.1748, 0.3426],
        [0.9377, 0.0413]])
tensor([[0.1748, 0.3426],
        [0.9377, 0.0413]])
tensor([[0.1748, 0.3426],
        [0.9377, 0.0413]])
tensor([[0.1748, 0.3426],
        [0.9377, 0.0413]])


### 2. Element Wise Operations

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)


tensor([[0.1127, 0.6972, 0.8760],
        [0.3163, 0.2989, 0.7827]])
tensor([[0.6531, 0.4221, 0.3149],
        [0.5815, 0.0656, 0.3457]])


In [65]:
# addition
print(a + b)

# subtraction
print(a - b)

# multiplication
print(a * b)

# division
print(a / b)

# mod
print(a % b)


tensor([[0.7658, 1.1193, 1.1909],
        [0.8978, 0.3645, 1.1284]])
tensor([[-0.5405,  0.2752,  0.5611],
        [-0.2652,  0.2333,  0.4369]])
tensor([[0.0736, 0.2943, 0.2759],
        [0.1839, 0.0196, 0.2706]])
tensor([[0.1725, 1.6519, 2.7817],
        [0.5440, 4.5538, 2.2639]])
tensor([[0.1127, 0.2752, 0.2462],
        [0.3163, 0.0363, 0.0912]])


In [72]:
c = torch.tensor([1, 2, 3, 4])

In [73]:
# abs
print(torch.abs(c))

tensor([1, 2, 3, 4])


In [74]:
# negative 
print(torch.neg(c))

tensor([-1, -2, -3, -4])


In [75]:
d = torch.tensor([1.9, 3.4, 4.5, 6.7])
d

tensor([1.9000, 3.4000, 4.5000, 6.7000])

In [78]:
# round
torch.round(d)

tensor([2., 3., 4., 7.])

In [79]:
# ceil
torch.ceil(d)

tensor([2., 4., 5., 7.])

In [ ]:
# floor => takes the integral part
torch.floor(d)

tensor([1., 3., 4., 6.])

In [81]:
# clamp => limits the values to a specified range
torch.clamp(d, min=2.0, max=5.0)

tensor([2.0000, 3.4000, 4.5000, 5.0000])

### 3. Reduction Operations


In [82]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 0., 9.],
        [0., 4., 3.]])

In [92]:
# sum
print(torch.sum(e))

# sum along columns (dim=0)
print(torch.sum(e, dim=0))

# sum along rows (dim=1)
print(torch.sum(e, dim=1))

# mean
print(torch.mean(e))

# median
print(torch.median(e))

# max and min => maximum and minimum values/Element in the tensor
print(torch.max(e))
print(torch.min(e))

# product 
print(torch.prod(e))

# standard deviation
print(torch.std(e))

# variance
print(torch.var(e))

# argmax and argmin => indices of maximum and minimum values
print(torch.argmax(e))
print(torch.argmin(e))


tensor(21.)
tensor([ 5.,  4., 12.])
tensor([14.,  7.])
tensor(3.5000)
tensor(3.)
tensor(9.)
tensor(0.)
tensor(0.)
tensor(3.3912)
tensor(11.5000)
tensor(2)
tensor(1)


### 4. Matrix Operations

In [94]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(2,3), low=0, high=10)

print(f)
print(g)

tensor([[9, 0, 7],
        [9, 3, 2]])
tensor([[3, 9, 7],
        [5, 3, 3]])


In [97]:
# matrix multiplication
print(torch.matmul(f, g.T))  

print(f * g)

tensor([[76, 66],
        [68, 60]])
tensor([[27,  0, 49],
        [45,  9,  6]])


In [98]:
vector_1 = torch.tensor([1, 2])
vector_2 = torch.tensor([3, 4])

# dot product
print(torch.dot(vector_1, vector_2))

tensor(11)


In [ ]:
# determinant
h = torch.det(torch.tensor([[1.0, 2.0], 
                            [3.0, 4.0]
                            ]))
print(h)

tensor(-2.)


### 5. Comparison Operations

In [103]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[0, 7, 7],
        [2, 4, 8]])
tensor([[9, 0, 6],
        [7, 1, 3]])


In [106]:
# greater than => checks every element if greater than corresponding element
print(i > j)

# less than => checks every element if less than corresponding element
print(i < j)

# equal => checks every element if equal to corresponding element
print(i == j)

# not equal => checks every element if not equal to corresponding element
print(i != j)


tensor([[False,  True,  True],
        [False,  True,  True]])
tensor([[ True, False, False],
        [ True, False, False]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])


### 6. Speacial Functions

In [107]:
k = torch.randint(size=(2,3), low=0, high=10)
k

tensor([[6, 4, 2],
        [1, 7, 2]])

In [109]:
# log
print(torch.log(k))

# exp
print(torch.exp(k))

# sqrt
print(torch.sqrt(k))



tensor([[1.7918, 1.3863, 0.6931],
        [0.0000, 1.9459, 0.6931]])
tensor([[ 403.4288,   54.5981,    7.3891],
        [   2.7183, 1096.6332,    7.3891]])
tensor([[2.4495, 2.0000, 1.4142],
        [1.0000, 2.6458, 1.4142]])


### Inplace Operations

In [111]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)


tensor([[0.7107, 0.7694, 0.8437],
        [0.5492, 0.6578, 0.5866]])
tensor([[0.7743, 0.1275, 0.1836],
        [0.5527, 0.8713, 0.8173]])


In [112]:
m.add_(n)  # in-place addition

tensor([[1.4850, 0.8970, 1.0273],
        [1.1018, 1.5292, 1.4040]])

### Copying a Tensor

In [113]:
a = torch.rand(2,3)
a

tensor([[0.8035, 0.8036, 0.8780],
        [0.9504, 0.4786, 0.2581]])

In [114]:
b = a
print(b)


tensor([[0.8035, 0.8036, 0.8780],
        [0.9504, 0.4786, 0.2581]])


In [ ]:
# put 10 on position [0][0]
a[0][0] = 10
a

tensor([[10.0000,  0.8036,  0.8780],
        [ 0.9504,  0.4786,  0.2581]])

In [116]:
print(id(a))

140127745974320
